/**
 * Where a command works differently from (or less than) FreeCAD's. `docs/02-web-ui.md`'s coverage
 * table marks these "partial"; `scripts/coverage.ts` reads them.
 */
export const PARTIAL: Record<string, string> = {
  Std_Open: "file picker (.FCStd opened, STEP/IGES/BREP/STL imported into a new document); no recent files",
  Std_Save: "saves on the server when the document has a server path, else downloads the .FCStd",
  Std_SaveAs: "server path (native backends) or download",
  Std_SaveCopy: "download",
  Std_Import: "STEP, IGES, BREP, STL, OBJ through Import with bytes",
  Std_Export: "STEP, IGES, BREP, STL, OBJ through Export, downloaded",
  Std_ProjectInfo: "read-only summary",
  Std_DuplicateSelection: "Document.copyObject through RunPython",
  PartDesign_DuplicateSelection: "Document.copyObject through RunPython",
  Std_Edit: "sketches and Part Design features",
  Std_Windows: "picks a window by name",
  Std_SendToPythonConsole: "defines obj / shp / elt on the server",
  Std_ViewScreenShot: "PNG of the 3D view, downloaded",
  Std_RandomColor: "view properties live in the page (no GUI document on the server)",
  Std_ToggleTransparency: "view properties live in the page",
  Std_ToggleSelectability: "view properties live in the page",
  Std_AlignToSelection: "planar faces",
  Part_Tube: "creates the Python feature; no task dialog",
  Part_Primitives: "all primitive types and placement; no edit of existing primitives",
  Part_Extrude: "normal / custom direction, lengths, symmetric, solid, taper",
  Part_Revolve: "Y axis through the origin, angle, solid",
  Part_Mirror: "YZ / XZ / XY planes through the origin",
  Part_Fillet: "one radius for the chosen edges",
  Part_Chamfer: "one size for the chosen edges",
  PartDesign_NewSketch: "on a base plane or a selected planar face",
  PartDesign_Pad: "type, length, side, reversed, taper, refine; no face picking for 'up to face'",
  PartDesign_Pocket: "as Pad",
  PartDesign_Revolution: "sketch V axis; angle, side, reversed",
  PartDesign_Groove: "sketch V axis; angle, side, reversed",
  PartDesign_Fillet: "selected edges/faces, radius",
  PartDesign_Chamfer: "selected edges/faces, size / type",
  PartDesign_Mirrored: "body YZ plane; plane choice in the property view",
  PartDesign_LinearPattern: "body X axis; length, occurrences",
  PartDesign_PolarPattern: "body Z axis; angle, occurrences",
  Sketcher_NewSketch: "XY / XZ / YZ with offset and reverse, or a selected planar face",
  Sketcher_CreateArc: "centre, start, end (counter-clockwise)",
  Sketcher_CreatePolyline: "line segments only (no arc mode)",
  Sketcher_ConstrainCoincidentUnified: "point on point, point on edge",
  Sketcher_Dimension: "distance for lines and points, radius for circles and arcs",
  Sketcher_ConstrainDistance: "line length or distance between two points",
  Sketcher_CancelSketch: "leaves without recomputing (edits already committed)",
};
